# This workflow will run tests using node and then publish a package to GitHub Container Registry and Docker Hub Regitry when a pushed into main branches
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A

name: Continuous Integration

on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches:
      - develop
      - main
      - master
      - master-i18n
      - cutomer/**
      - test**
  release:
    types:
      - published

jobs:

  # Publish docker image in Github Container Registry to application
  # Build dist application adv-default-theme
  build-app:
    name: Build dist adv-default-theme
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Node configuration
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Compress files for application dist
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: 'adv-default-theme.zip'
          path: './'
          exclusions: './dist ./docker ./docs'

      - name: Upload app as artifact
        uses: actions/upload-artifact@v3
        with:
          name: adv-default-theme
          path: ./adv-default-theme.zip
